# Generated by Django 3.2.14 on 2023-04-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinproject',
            name='project_manager',
            field=models.CharField(default='', max_length=20),
        ),
    ]
