# Generated by Django 3.2.14 on 2023-06-07 11:05

import api.meta_tagging.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTagging',
            fields=[
                ('meta_tagging_id', models.CharField(default=api.meta_tagging.models.generate_unique_code_meta_tagging, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MetaTaggingLabels',
            fields=[
                ('label_id', models.CharField(default=api.meta_tagging.models.generate_unique_code_label, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=7)),
                ('meta_tagging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta_tagging.metatagging')),
            ],
        ),
    ]
