# Generated by Django 3.2.14 on 2023-06-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta_tagging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metatagging',
            name='test',
            field=models.CharField(default='1', max_length=500),
        ),
    ]
