# Generated by Django 3.2.14 on 2023-06-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_tagging', '0002_metatagging_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metatagging',
            name='test',
        ),
    ]
